package com.android.nextai.ui.component.markdown.parser

import android.util.Log
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.android.nextai.ui.component.markdown.MarkdownNode
import com.android.nextai.ui.component.markdown.parser.MarkdownParser.parseMarkDown
import com.android.nextai.ui.component.markdown.parser.MarkdownParser.replaceLatexDelimiters

/**
 * Incremental Markdown parser
 *
 * This parser caches chunk string fragments generated by streaming, and caches the complete
 * stream-generated text in the parser. Before parsing, the original cached text is adjusted to make
 * it **compatible with tables and standard latex formulas**.
 *
 * A long text consists of multiple block-level Markdown nodes. The parser divides the parsing nodes
 * into two categories: stable nodes that have completed parsing, and nodes that are currently parsing
 * but not yet fully closed.
 */
class MarkdownIncrementalParser {
    companion object {
        private const val TAG = "MarkdownIncrementalParser"
    }

    /** Block-level Markdown nodes that are stable and unchanging. **/
    val stableNodes = mutableStateListOf<MarkdownNode>()

    /** A list of terminal nodes that are currently being streamed and are not yet stable. **/
    var pendingNodes by mutableStateOf<List<MarkdownNode>>(emptyList())
        private set

    /** A full-text buffer originally generated by llm model。 **/
    private val rawFullTextBuffer = StringBuilder()

    /** Recorded in the **normalized Markdown**, the text length has been successfully solidified
     * into stableNodes. **/
    private var stableTextLength = 0

    /**
     * Full text setting (used for: static scenarios such as historical message initialization and
     * database recovery)
     *
     * External input of the original text, internal unified escape.
     */
    fun setContent(rawContent: String) {
        reset()
        if (rawContent.isEmpty()) return

        rawFullTextBuffer.append(rawContent)
        Log.d(TAG, "raw: $rawContent")
        // 转换为标准 Markdown
        val formatted = replaceLatexDelimiters(rawContent)
        Log.d(TAG, "formatted: $formatted")
        val result = parseMarkDown(formatted)

        stableNodes.addAll(result.nodes)
        // 静态加载，全量直接视为标准坐标系下的稳定长度
        stableTextLength = formatted.length
    }

    /**
     * Incremental addition function.
     *
     * @param deltaRawText This is just the newly generated text chunk of the current llm model.
     */
    fun appendDelta(deltaRawText: String) {
        if (deltaRawText.isEmpty()) return

        // 1. Record the original original text.
        rawFullTextBuffer.append(deltaRawText)

        // 2. Clean the latest full original text to obtain the full formatted Markdown.
        val fullFormattedText = replaceLatexDelimiters(rawFullTextBuffer.toString())

        // 3. Using the unique absolute anchor stableTextLength (already stable length).
        // Directly extract the currently unstable string[Active Text] from the full formatted text.
        if (fullFormattedText.length < stableTextLength) {
            // The total length is even smaller than the length already solidified.
            reset()
            setContent(rawFullTextBuffer.toString())
            return
        }

        val activeText = fullFormattedText.substring(stableTextLength)
        if (activeText.isEmpty()) return

        // 4. Strat to parse the full formatted text.
        val result = parseMarkDown(md = activeText)
        val nodes = result.nodes
        if (nodes.isEmpty()) {
            return
        }

        // 5. State Machine Advancement.
        if (nodes.size > 1) {
            // Multiple block level nodes appear, indicating that the previous node has been "closed/stabilized."
            val stablePart = nodes.dropLast(1)
            stableNodes.addAll(stablePart)

            // The last node is still unclosed, and insert the pending driver for UI rendering.
            pendingNodes = listOf(nodes.last())

            // 6. parsedLength is calculated based on activeText).
            stableTextLength += result.parsedLength
        } else {
            // If there is only one node, it means the current paragraph/formula is still getting
            // grow, so insert pending.
            pendingNodes = nodes
        }
    }

    /**
     * End of streaming (called when the llm streaming is done).
     */
    fun complete() {
        val currentFullFormatted = replaceLatexDelimiters(rawFullTextBuffer.toString())
        val activeText = currentFullFormatted.substring(stableTextLength)

        if (activeText.isNotEmpty()) {
            val result = parseMarkDown(md = activeText)
            if (result.nodes.isNotEmpty()) {
                stableNodes.addAll(result.nodes)
            }
        }
        pendingNodes = emptyList()
        stableTextLength = currentFullFormatted.length
    }

    /**
     * Reset all states.
     */
    fun reset() {
        stableNodes.clear()
        pendingNodes = emptyList()
        rawFullTextBuffer.clear()
        stableTextLength = 0
    }
}